# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 95c28d60bb6f9ab45494cb75910f328b
  secret_key: 04e8f259518a7c35996129f3102a9984
  canvas_page_name: climatetest
  callback_url: http://bymatthew.com:8888
  pretty_errors: true
  tunnel:
    public_host_username: wastro
    public_host: bymatthew.com
    public_port: 4007
    local_port: 3000

test:
  api_key: 95c28d60bb6f9ab45494cb75910f328b
  secret_key: 04e8f259518a7c35996129f3102a9984
  canvas_page_name: climatetest
  callback_url: http://bymatthew.com:8888
  pretty_errors: true
  tunnel:
    public_host_username: wastro
    public_host: bymatthew.com
    public_port: 4007
    local_port: 3000

production:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:  
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
